// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgYaPjCDbO6Bs5wkdvC3Prr46MWQbD5Zc',
    appId: '1:1029173790499:web:7800ca39c7a53095272e96',
    messagingSenderId: '1029173790499',
    projectId: 'weatherdashboard-e6443',
    authDomain: 'weatherdashboard-e6443.firebaseapp.com',
    storageBucket: 'weatherdashboard-e6443.firebasestorage.app',
    measurementId: 'G-WJNJQ6VK25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTmgPsuNl7FHYD27vkh1AXu2dsw5rqbmw',
    appId: '1:1029173790499:android:8f097eab16f0af4a272e96',
    messagingSenderId: '1029173790499',
    projectId: 'weatherdashboard-e6443',
    storageBucket: 'weatherdashboard-e6443.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq7Q6y0kDlTCP2sROihWDTLJ7N_DQzNvY',
    appId: '1:1029173790499:ios:8512365a912150d8272e96',
    messagingSenderId: '1029173790499',
    projectId: 'weatherdashboard-e6443',
    storageBucket: 'weatherdashboard-e6443.firebasestorage.app',
    iosBundleId: 'com.example.weatherDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq7Q6y0kDlTCP2sROihWDTLJ7N_DQzNvY',
    appId: '1:1029173790499:ios:8512365a912150d8272e96',
    messagingSenderId: '1029173790499',
    projectId: 'weatherdashboard-e6443',
    storageBucket: 'weatherdashboard-e6443.firebasestorage.app',
    iosBundleId: 'com.example.weatherDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgYaPjCDbO6Bs5wkdvC3Prr46MWQbD5Zc',
    appId: '1:1029173790499:web:086d79b25a212637272e96',
    messagingSenderId: '1029173790499',
    projectId: 'weatherdashboard-e6443',
    authDomain: 'weatherdashboard-e6443.firebaseapp.com',
    storageBucket: 'weatherdashboard-e6443.firebasestorage.app',
    measurementId: 'G-238NGH6Z3F',
  );
}
